ab_user:
    resource: "@ABUserBundle/Resources/config/routing.yml"
    prefix:   /

ab_platform:
    resource: "@ABPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

ab_core:
    resource: "@ABCoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern: /login
    defaults: {_controller: ABUserBundle:Security:login}

login_check:
    pattern: /login_check

logout:
    pattern: /logout

