ab_panier:
    resource: "@ABPanierBundle/Resources/config/routing.yml"
    prefix:   /

ab_platform:
    resource: "@ABPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

ab_core:
    resource: "@ABCoreBundle/Resources/config/routing.yml"
    prefix:   /


