ab_platform_accueil:
    path:     /accueil/{page}
    defaults: { _controller: ABPlatformBundle:Book:accueil,page: 2 }
    requirements:
        page: \d*

ab_platform_add:
    path:    /add
    defaults: {_controller: ABPLatformBundle:Book:add}

ab_platform_delete:
    path:    /delete/{id}
    defaults: {_controller: ABPlatformBundle:Book:delete}
    requirements:
        id: \d+

ab_platform_update:
    path:    /update/{id}
    defaults: {_controller: ABPlatformBundle:Book:update}
    requirements:
        id: \d+

ab_platform_read:
    path:    /read
    defaults: {_controller: ABPlatformBundle:Book:read}
