ab_platform_add:
    path:    /add
    defaults: {_controller: ABPlatformBundle:Book:add}

ab_platform_delete:
    path:    /delete/{id}
    defaults: {_controller: ABPlatformBundle:Book:delete}
    requirements:
        id: \d+

ab_platform_update:
    path:    /update/{id}
    defaults: {_controller: ABPlatformBundle:Book:update}
    requirements:
        id: \d+

ab_platform_read:
    path:    /read
    defaults: {_controller: ABPlatformBundle:Book:read}

ab_platform_selection:
    path:    /selection/{id}
    defaults: {_controller: ABPlatformBundle:Book:ajout}
    requirements:
        id: \d*

ab_platform_panier:
    path:    /panier/{id}/{titre}/{auteur}/{prix}/{quantite}
    defaults: {_controller: ABPlatformBundle:Book:updatepanier}
    requirements:
        id: \d*

ab_platform_validation:
    path:    /validation/{id}
    defaults: {_controller: ABPlatformBundle:Panier:validation}
    requirements:
        id: \d*

ab_platform_compte:
    path:    /compte
    default: {-controller: ABPlatformBundle:Panier:compteAction}