ab_platform_add:
    path:    /add
    defaults: {_controller: ABPlatformBundle:Book:add}

ab_platform_delete:
    path:    /delete/{id}
    defaults: {_controller: ABPlatformBundle:Book:delete}
    requirements:
        id: \d+

ab_platform_update:
    path:    /update/{id}
    defaults: {_controller: ABPlatformBundle:Book:update}
    requirements:
        id: \d+

ab_platform_read:
    path:    /read
    defaults: {_controller: ABPlatformBundle:Book:read}

ab_platform_panier:
    path:    /panier/{id}/{titre}/{auteur}/{prix}
    defaults: {_controller: ABPlatformBundle:Book:ajout}
    requirements:
        id: \d*