ab_panier_ajout:
    path:     /panier
    defaults: { _controller: ABPanierBundle:Panier:add }

ab_panier_paiement:
    path:     /panier/paiement
    defaults: {_controller: ABPanierBundle:Panier:paiement}
