<?php

namespace AB\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    /*public function getachatBook($quantiteDispo){
        $qb=$this->createQueryBuilder('b');
        $qb->where('b.quantite_dispo < :quantite_dispo')
            ->setParameter('quantite_dispo','b.quantite_dispo'-$quantiteDispo);
        return $qb->getQuery()->getResult();
    }*/
}
