<?php

namespace AB\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookPanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookPanierRepository extends EntityRepository
{
}
